//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MESsoftware1.sfcBatchPack {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiAddCheckMarkAndPackForsfcBatchServiceBinding", Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class MiAddCheckMarkAndPackForsfcBatchServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback miAddCheckMarkAndPackForsfcBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContainerCustomDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInternationalSfcOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiAddCheckMarkAndPackForsfcBatchServiceService() {
            this.Url = global::MESsoftware1.Properties.Settings.Default.MESsoftware1_sfcBatchPack_MiAddCheckMarkAndPackForsfcBatchServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event miAddCheckMarkAndPackForsfcBatchCompletedEventHandler miAddCheckMarkAndPackForsfcBatchCompleted;
        
        /// <remarks/>
        public event getContainerCustomDataCompletedEventHandler getContainerCustomDataCompleted;
        
        /// <remarks/>
        public event getInternationalSfcCompletedEventHandler getInternationalSfcCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("miAddCheckMarkAndPackForsfcBatchResponse", Namespace="http://sfcBatchPack.ws.atlmes.com/")]
        public miAddCheckMarkAndPackForsfcBatchResponse miAddCheckMarkAndPackForsfcBatch([System.Xml.Serialization.XmlElementAttribute("miAddCheckMarkAndPackForsfcBatch", Namespace="http://sfcBatchPack.ws.atlmes.com/")] miAddCheckMarkAndPackForsfcBatch miAddCheckMarkAndPackForsfcBatch1) {
            object[] results = this.Invoke("miAddCheckMarkAndPackForsfcBatch", new object[] {
                        miAddCheckMarkAndPackForsfcBatch1});
            return ((miAddCheckMarkAndPackForsfcBatchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void miAddCheckMarkAndPackForsfcBatchAsync(miAddCheckMarkAndPackForsfcBatch miAddCheckMarkAndPackForsfcBatch1) {
            this.miAddCheckMarkAndPackForsfcBatchAsync(miAddCheckMarkAndPackForsfcBatch1, null);
        }
        
        /// <remarks/>
        public void miAddCheckMarkAndPackForsfcBatchAsync(miAddCheckMarkAndPackForsfcBatch miAddCheckMarkAndPackForsfcBatch1, object userState) {
            if ((this.miAddCheckMarkAndPackForsfcBatchOperationCompleted == null)) {
                this.miAddCheckMarkAndPackForsfcBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmiAddCheckMarkAndPackForsfcBatchOperationCompleted);
            }
            this.InvokeAsync("miAddCheckMarkAndPackForsfcBatch", new object[] {
                        miAddCheckMarkAndPackForsfcBatch1}, this.miAddCheckMarkAndPackForsfcBatchOperationCompleted, userState);
        }
        
        private void OnmiAddCheckMarkAndPackForsfcBatchOperationCompleted(object arg) {
            if ((this.miAddCheckMarkAndPackForsfcBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.miAddCheckMarkAndPackForsfcBatchCompleted(this, new miAddCheckMarkAndPackForsfcBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getContainerCustomDataResponse", Namespace="http://sfcBatchPack.ws.atlmes.com/")]
        public getContainerCustomDataResponse getContainerCustomData([System.Xml.Serialization.XmlElementAttribute("getContainerCustomData", Namespace="http://sfcBatchPack.ws.atlmes.com/")] getContainerCustomData getContainerCustomData1) {
            object[] results = this.Invoke("getContainerCustomData", new object[] {
                        getContainerCustomData1});
            return ((getContainerCustomDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getContainerCustomDataAsync(getContainerCustomData getContainerCustomData1) {
            this.getContainerCustomDataAsync(getContainerCustomData1, null);
        }
        
        /// <remarks/>
        public void getContainerCustomDataAsync(getContainerCustomData getContainerCustomData1, object userState) {
            if ((this.getContainerCustomDataOperationCompleted == null)) {
                this.getContainerCustomDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContainerCustomDataOperationCompleted);
            }
            this.InvokeAsync("getContainerCustomData", new object[] {
                        getContainerCustomData1}, this.getContainerCustomDataOperationCompleted, userState);
        }
        
        private void OngetContainerCustomDataOperationCompleted(object arg) {
            if ((this.getContainerCustomDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContainerCustomDataCompleted(this, new getContainerCustomDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getInternationalSfcResponse", Namespace="http://sfcBatchPack.ws.atlmes.com/")]
        public getInternationalSfcResponse getInternationalSfc([System.Xml.Serialization.XmlElementAttribute("getInternationalSfc", Namespace="http://sfcBatchPack.ws.atlmes.com/")] getInternationalSfc getInternationalSfc1) {
            object[] results = this.Invoke("getInternationalSfc", new object[] {
                        getInternationalSfc1});
            return ((getInternationalSfcResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getInternationalSfcAsync(getInternationalSfc getInternationalSfc1) {
            this.getInternationalSfcAsync(getInternationalSfc1, null);
        }
        
        /// <remarks/>
        public void getInternationalSfcAsync(getInternationalSfc getInternationalSfc1, object userState) {
            if ((this.getInternationalSfcOperationCompleted == null)) {
                this.getInternationalSfcOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInternationalSfcOperationCompleted);
            }
            this.InvokeAsync("getInternationalSfc", new object[] {
                        getInternationalSfc1}, this.getInternationalSfcOperationCompleted, userState);
        }
        
        private void OngetInternationalSfcOperationCompleted(object arg) {
            if ((this.getInternationalSfcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInternationalSfcCompleted(this, new getInternationalSfcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class miAddCheckMarkAndPackForsfcBatch {
        
        private miAddCheckMarkAndPackForsfcRequest miAddCheckMarkAndPackForsfcRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public miAddCheckMarkAndPackForsfcRequest MiAddCheckMarkAndPackForsfcRequest {
            get {
                return this.miAddCheckMarkAndPackForsfcRequestField;
            }
            set {
                this.miAddCheckMarkAndPackForsfcRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class miAddCheckMarkAndPackForsfcRequest {
        
        private string siteField;
        
        private string containerField;
        
        private string containerNumberField;
        
        private bool checkMarkingField;
        
        private string activityField;
        
        private string operationField;
        
        private string resourceField;
        
        private bool closeContainerField;
        
        private string packGroupField;
        
        private requestSfcDetail[] sfcListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string containerNumber {
            get {
                return this.containerNumberField;
            }
            set {
                this.containerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool checkMarking {
            get {
                return this.checkMarkingField;
            }
            set {
                this.checkMarkingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool closeContainer {
            get {
                return this.closeContainerField;
            }
            set {
                this.closeContainerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string packGroup {
            get {
                return this.packGroupField;
            }
            set {
                this.packGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sfcList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public requestSfcDetail[] sfcList {
            get {
                return this.sfcListField;
            }
            set {
                this.sfcListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class requestSfcDetail {
        
        private string packGroupCodeField;
        
        private string sequenceField;
        
        private string sfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string packGroupCode {
            get {
                return this.packGroupCodeField;
            }
            set {
                this.packGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfc {
            get {
                return this.sfcField;
            }
            set {
                this.sfcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class getInternationalSfcResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class getInternationalSfc {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private dynamicQuery arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dynamicQuery arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class dynamicQuery {
        
        private int maxRowsField;
        
        private bool overrideMaxRowCountField;
        
        private int rowStartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool overrideMaxRowCount {
            get {
                return this.overrideMaxRowCountField;
            }
            set {
                this.overrideMaxRowCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rowStart {
            get {
                return this.rowStartField;
            }
            set {
                this.rowStartField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class data {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class getContainerCustomDataResponse {
        
        private data returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public data @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class getContainerCustomData {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private dynamicQuery arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dynamicQuery arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class responseSfcDetail {
        
        private string containerNumberField;
        
        private string sfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string containerNumber {
            get {
                return this.containerNumberField;
            }
            set {
                this.containerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfc {
            get {
                return this.sfcField;
            }
            set {
                this.sfcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class miAddCheckMarkAndPackForsfcResponse {
        
        private int codeField;
        
        private string messageField;
        
        private responseSfcDetail[] sfcListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sfcList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseSfcDetail[] sfcList {
            get {
                return this.sfcListField;
            }
            set {
                this.sfcListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sfcBatchPack.ws.atlmes.com/")]
    public partial class miAddCheckMarkAndPackForsfcBatchResponse {
        
        private miAddCheckMarkAndPackForsfcResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public miAddCheckMarkAndPackForsfcResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void miAddCheckMarkAndPackForsfcBatchCompletedEventHandler(object sender, miAddCheckMarkAndPackForsfcBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class miAddCheckMarkAndPackForsfcBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal miAddCheckMarkAndPackForsfcBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public miAddCheckMarkAndPackForsfcBatchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((miAddCheckMarkAndPackForsfcBatchResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void getContainerCustomDataCompletedEventHandler(object sender, getContainerCustomDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContainerCustomDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContainerCustomDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getContainerCustomDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getContainerCustomDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void getInternationalSfcCompletedEventHandler(object sender, getInternationalSfcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInternationalSfcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInternationalSfcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getInternationalSfcResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getInternationalSfcResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591