//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MESsoftware1.micheckMarkAnddcPackForSfc {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiCheckMarkAndDcPackForsfcServiceBinding", Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")]
    public partial class MiCheckMarkAndDcPackForsfcServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback miCheckMarkAndDCForSfcOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiCheckMarkAndDcPackForsfcServiceService() {
            this.Url = global::MESsoftware1.Properties.Settings.Default.MESsoftware1_micheckMarkAnddcPackForSfc_MiCheckMarkAndDcPackForsfcServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event miCheckMarkAndDCForSfcCompletedEventHandler miCheckMarkAndDCForSfcCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("miCheckMarkAndDCForSfcResponse", Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")]
        public miCheckMarkAndDCForSfcResponse miCheckMarkAndDCForSfc([System.Xml.Serialization.XmlElementAttribute("miCheckMarkAndDCForSfc", Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")] miCheckMarkAndDCForSfc miCheckMarkAndDCForSfc1) {
            object[] results = this.Invoke("miCheckMarkAndDCForSfc", new object[] {
                        miCheckMarkAndDCForSfc1});
            return ((miCheckMarkAndDCForSfcResponse)(results[0]));
        }
        
        /// <remarks/>
        public void miCheckMarkAndDCForSfcAsync(miCheckMarkAndDCForSfc miCheckMarkAndDCForSfc1) {
            this.miCheckMarkAndDCForSfcAsync(miCheckMarkAndDCForSfc1, null);
        }
        
        /// <remarks/>
        public void miCheckMarkAndDCForSfcAsync(miCheckMarkAndDCForSfc miCheckMarkAndDCForSfc1, object userState) {
            if ((this.miCheckMarkAndDCForSfcOperationCompleted == null)) {
                this.miCheckMarkAndDCForSfcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmiCheckMarkAndDCForSfcOperationCompleted);
            }
            this.InvokeAsync("miCheckMarkAndDCForSfc", new object[] {
                        miCheckMarkAndDCForSfc1}, this.miCheckMarkAndDCForSfcOperationCompleted, userState);
        }
        
        private void OnmiCheckMarkAndDCForSfcOperationCompleted(object arg) {
            if ((this.miCheckMarkAndDCForSfcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.miCheckMarkAndDCForSfcCompleted(this, new miCheckMarkAndDCForSfcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")]
    public partial class miCheckMarkAndDCForSfc {
        
        private CheckMarkAndDCForSfcRequest checkMarkAndDcForSfcRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CheckMarkAndDCForSfcRequest CheckMarkAndDcForSfcRequest {
            get {
                return this.checkMarkAndDcForSfcRequestField;
            }
            set {
                this.checkMarkAndDcForSfcRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")]
    public partial class CheckMarkAndDCForSfcRequest {
        
        private string sfcField;
        
        private string siteField;
        
        private string operationField;
        
        private string resourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfc {
            get {
                return this.sfcField;
            }
            set {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")]
    public partial class checkMarkAndDcForSfcResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private string sfcField;
        
        private string groupCodeField;
        
        private string groupBasisField;
        
        private string labelRemarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfc {
            get {
                return this.sfcField;
            }
            set {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string groupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string groupBasis {
            get {
                return this.groupBasisField;
            }
            set {
                this.groupBasisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string labelRemarks {
            get {
                return this.labelRemarksField;
            }
            set {
                this.labelRemarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://micheckmarkanddcpackforsfc.ws.atlmes.com/")]
    public partial class miCheckMarkAndDCForSfcResponse {
        
        private checkMarkAndDcForSfcResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public checkMarkAndDcForSfcResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void miCheckMarkAndDCForSfcCompletedEventHandler(object sender, miCheckMarkAndDCForSfcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class miCheckMarkAndDCForSfcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal miCheckMarkAndDCForSfcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public miCheckMarkAndDCForSfcResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((miCheckMarkAndDCForSfcResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591