//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESsoftware1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmes4p093.catlbattery.com:50300/atlmeswebservice/MiCheckMarkAndDcPackFors" +
            "fcServiceService")]
        public string MESsoftware1_micheckMarkAnddcPackForSfc_MiCheckMarkAndDcPackForsfcServiceService {
            get {
                return ((string)(this["MESsoftware1_micheckMarkAnddcPackForSfc_MiCheckMarkAndDcPackForsfcServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmes4p093.catlbattery.com:50300/atlmeswebservice/MiAddCheckMarkAndPackFor" +
            "sfcBatchServiceService")]
        public string MESsoftware1_sfcBatchPack_MiAddCheckMarkAndPackForsfcBatchServiceService {
            get {
                return ((string)(this["MESsoftware1_sfcBatchPack_MiAddCheckMarkAndPackForsfcBatchServiceService"]));
            }
        }
    }
}
